kind: pipeline
name: default

steps:
  - name: rubocop
    image: ruby:2.7.2
    commands:
      - bundle install --jobs=3 --retry=3
      - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s && chmod +x ./bin/reviewdog
      - bundle exec rubocop | ./bin/reviewdog -f=rubocop -reporter=github-pr-check
    environment:
      REVIEWDOG_GITHUB_API_TOKEN:
        from_secret: REVIEWDOG_GITHUB_API_TOKEN

trigger:
  ref:
    - refs/pull/*/head
