kind: pipeline
name: default

steps:
  - name: rubocop
    image: ruby:2.7.2
    commands:
      - bundle install --jobs=3 --retry=3
      - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s && chmod +x ./reviewdog
      - bundle exec rubocop | ./reviewdog -f=rubocop -reporter=github-pr-review
