kind: pipeline
name: default

steps:
  - name: rubocop
    image: ruby:2.7.2
    commands:
      - bundle install --jobs=3 --retry=3
      - curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog
      - bundle exec rubocop | ./reviewdog -f=rubocop -reporter=github-pr-review
