version: '3'
services:
    api:
      build:
        dockerfile: docker/api/Dockerfile
        context: .
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      volumes:
        - .:/app
      ports:
        - 3000:3000
    web:
      build:
        dockerfile: docker/web/Dockerfile
        context: .
      volumes:
        - ./web:/web
      ports:
        - 3030:3030
      command: sh -c "pwd && yarn install && yarn dev"


